name: 'fivetwo'
 
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
  
    
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 'pypy-3.7'
          architecture: 'x64'

      - name: 'Run Pip1' 
        run: pip3 install selenium
#       - name: 'Run Pip2' 
#         run: pip3 install json
#       - name: 'Run Pip3' 
#         run: pip3 install time

        
      - name: 'Run baiduPush.sh' # 步骤二，执行sh命令文件
        run: python3 fivetwo.py   # 运行命令。（注意，运行目录是仓库根目录）
